# This the the Flatmoney market config file.

# Owner of the protocol contracts which include: ProxyAdmins, FlatcoinVault & KeeperFee.
# Should be a Gnosis Safe multisig to use other scripts.
owner = "0x1677640787891022efEC86828BC386828c68d2aA"

# Oracle data for the market is added in the OracleData table.
# If the data already exists in the oracle module (verified by checking the address of the asset), 
# then the scripts will not add the data.
# This is an optional table. However, if the oracle doesn't exist, the market won't function.
[OracleData]
name = "WBTC"
address = "0x2f2a2543B76A4166549F7aaB2e75Bef0aefC5B0f"                                        # WBTC on Arbitrum
maxDiffPercent = "10000000000000000"                                                          # 1e16 => 1%
offchainOracle.maxAge = 86_400                                                                # 86400 seconds => 24 hours
offchainOracle.minConfidenceRatio = 50                                                        # 100/50 => +-2% price deviation acceptable
offchainOracle.priceId = "0xc9d8b075a5c69303365ae23633d4e085199bf5c520a3b90fed1322a0342ffc33" # Pyth WBTC/USD ID
onchainOracle.maxAge = 90_000                                                                 # 90_000 seconds => 25 hours
onchainOracle.oracleContract = "0xd0C7101eACbB49F3deCcCc166d238410D6D46d57"                   # WBTC/USD Chainlink oracle on Arbitrum

[Modules]

[Modules.FlatcoinVault]
isUpgradeable = true
proxyType = "beacon"
collateral = "0x2f2a2543B76A4166549F7aaB2e75Bef0aefC5B0f"                                              # WBTC on Arbitrum
leverageTradingFee = "10000000000000000"                                                               # 1e16 => 1%
maxDeltaError = 100                                                                                    # 1e2
maxPositions = "3"                                                                                     # Only for Toros vaults
protocolFeeRecipient = "0x1677640787891022efEC86828BC386828c68d2aA"                                    # Flatmoney owner
protocolFeePercentage = "200000000000000000"                                                           # 20e16 => 20%
skewFractionMax = "1000000000000000000"                                                                # 1e18 => 100%
stableCollateralCap = "115792089237316195423570985008687907853269984665640564039457584007913129639935" # type(uint256).max => No cap.
stableWithdrawFee = "500000000000000"                                                                  # 0.05e16 => 0.05%                                                               

[Modules.LeverageModule]
isUpgradeable = true
proxyType = "beacon"
leverageMax = "5000000000000000000" # 5e18 => 5x
leverageMin = "1100000000000000000" # 11e17 => 1.1e18 => 1.1x
marginMin = "50000"                 # 0.0005e8 WBTC => ~50 USD

[Modules.StableModule]
isUpgradeable = true
proxyType = "beacon"

[Modules.OptionsControllerModule]
isUpgradeable = true
proxyType = "beacon"
maxFundingVelocity = "2000000000000000"          # 0.2e16 => 0.2% daily funding per day
maxVelocitySkew = "100000000000000000"           # 1e17 => 10%
minFundingRate = "0"                             # Min funding will be 0%.
targetSizeCollateralRatio = "800000000000000000" # 45/55 target => Skew ratio 0.8 as we want 45/55 target size-collateral ratio (80% utilization) for Toros.

[Modules.OrderAnnouncementModule]
isUpgradeable = true
proxyType = "beacon"
minExecutabilityAge = 5                      # 5 seconds
minDepositAmountUSD = "10000000000000000000" # $10

[Modules.OrderExecutionModule]
isUpgradeable = true
proxyType = "beacon"
maxExecutabilityAge = 60 # 60 seconds

[Modules.LiquidationModule]
isUpgradeable = true
proxyType = "beacon"
liquidationBufferRatio = "10000000000000000"       # 1e16 => 1%
liquidationFeeLowerBound = "2000000000000000000"   # 2 USD
liquidationFeeRatio = "5000000000000000"           # 5e15 => 0.5e16 => 0.5%
liquidationFeeUpperBound = "100000000000000000000" # 100 USD

[Modules.ArbKeeperFee]
isUpgradeable = false
assetToPayWith = "0x2f2a2543B76A4166549F7aaB2e75Bef0aefC5B0f" # WBTC on Arbitrum
ethOracle = "0x639Fe6ab55C921f74e7fac1ee960C0B6293ba612"      # Arbitrum mainnet ETH/USD Chainlink oracle
keeperFeeLowerBound = "150000000000000000"                    # 15 cents => $0.15
keeperFeeUpperBound = "30000000000000000000"                  # 30 USD
profitMarginPercent = "300000000000000000"                    # 30e16 => 30%
gasUnitsL1 = 30_000
gasUnitsL2 = 1_200_000
stalenessPeriod = 90_000                                      # 90_000 seconds => 25 hours

[Modules.OptionViewer]
isUpgradeable = false

# Note that the following contract isn't technically a module but is unique to this market.
[Modules.FlatZapper]
isUpgradeable = true
proxyType = "transparent"
owner = "0x1677640787891022efEC86828BC386828c68d2aA"      # Should be a Gnosis Safe multisig to use other scripts.
collateral = "0x2f2a2543B76A4166549F7aaB2e75Bef0aefC5B0f" # WBTC on Arbitrum
permit2 = "0x000000000022D473030F116dDEE9F6B43aC78BA3"    # As found in https://blog.uniswap.org/permit2-and-universal-router
weth = "0x82aF49447D8a07e3bd95BD0d56f35241523fBab1"       # WETH on Arbitrum
