name: Run Lint Checks

on:
  pull_request:
    branches:
      - master
    types:
      - opened
      - synchronize

jobs:
  lint:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
          cache: "pnpm"
      - name: Install Dependencies
        run: pnpm install --frozen-lockfile
        working-directory: ./
      - name: Run Solhint
        run: pnpm lint:sol
        working-directory: ./
      - name: Run Prettier
        run: pnpm prettier:check
        working-directory: ./
