name: Run Fuzz Tests

on:
  schedule:
    - cron: "0 4 * * 0" # at 4:00 AM UTC every Sunday

jobs:
  test:
    name: Fuzz tests deep run
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
      - name: Run tests
        run: FOUNDRY_PROFILE=deepci forge test -vvv --match-test '(test_fuzz:?)'
